transformer_additional_kwargs:
  patch_3d:                                   false
  fake_3d:                                    false
  basic_block_type:                           "selfattentiontemporal"
  time_position_encoding_before_transformer:  true

noise_scheduler_kwargs:
  beta_start:    0.0001
  beta_end:      0.02
  beta_schedule: "linear"
  steps_offset:  1

vae_kwargs:
  enable_magvit: false